// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkL8UJBHqvkiZPnOX7zpjgtIZICoFTPhE',
    appId: '1:352431701190:web:29c6d3e0fad245187b2bc7',
    messagingSenderId: '352431701190',
    projectId: 'bookappauth-b507e',
    authDomain: 'bookappauth-b507e.firebaseapp.com',
    storageBucket: 'bookappauth-b507e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJEcf1m9YbkStb6b8Vk3PWx83YCjqp0Zk',
    appId: '1:352431701190:android:60397c194f27be5f7b2bc7',
    messagingSenderId: '352431701190',
    projectId: 'bookappauth-b507e',
    storageBucket: 'bookappauth-b507e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBALDNUvWmCNk5sEvAkSbqQnR6hhKrZPw',
    appId: '1:352431701190:ios:8c65b792391798ef7b2bc7',
    messagingSenderId: '352431701190',
    projectId: 'bookappauth-b507e',
    storageBucket: 'bookappauth-b507e.firebasestorage.app',
    iosBundleId: 'com.example.bookhaven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBALDNUvWmCNk5sEvAkSbqQnR6hhKrZPw',
    appId: '1:352431701190:ios:8c65b792391798ef7b2bc7',
    messagingSenderId: '352431701190',
    projectId: 'bookappauth-b507e',
    storageBucket: 'bookappauth-b507e.firebasestorage.app',
    iosBundleId: 'com.example.bookhaven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkL8UJBHqvkiZPnOX7zpjgtIZICoFTPhE',
    appId: '1:352431701190:web:cb88077cc13e27527b2bc7',
    messagingSenderId: '352431701190',
    projectId: 'bookappauth-b507e',
    authDomain: 'bookappauth-b507e.firebaseapp.com',
    storageBucket: 'bookappauth-b507e.firebasestorage.app',
  );

}